# Generated by Django 5.0.2 on 2024-04-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mail_address',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
