# Generated by Django 5.0.2 on 2024-04-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userauth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='mail_address',
            new_name='email',
        ),
    ]
